name: Sync Teacher Calendar

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Google Calendar
        run: |
          curl -L "https://calendar.google.com/calendar/ical/f23db1d5d9534184c7d314f59cf5365548a1170b3921dd85e657d83d53cefac3%40group.calendar.google.com/public/basic.ics" -o calendar.ics

      - name: Commit updated calendar
        run: |
          git config user.name "calendar-bot"
          git config user.email "bot@github.com"
          git add calendar.ics
          git commit -m "Update calendar" || echo "No changes"
          git push
